create table books
(
  book_id integer primary key generated by default as identity,
  title varchar (255),
  publication_year INTEGER,
  in_stock BOOLEAN DEFAULT false,
  author_id INTEGER REFERENCES authors(author_id) NOT NULL
)